name: 本番環境へのデプロイ (himmme.com)

on:
  workflow_dispatch:

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://himmme.com

    steps:
      - uses: actions/checkout@v4

      - name: Upload to Xserver (Production)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SFTP_HOST_PROD }}
          username: ${{ secrets.SFTP_USER_PROD }}
          password: ${{ secrets.SFTP_PASS_PROD }}
          source: "./*"
          target: ${{ secrets.SFTP_PATH_PROD }}
          rm: true
