name: テストアップ (test.himmme.com)

on:
  push:
    branches:
      - main

jobs:
  deploy-staging:
    runs-on: ubuntu-latest

    environment:
      name: staging
      url: https://test.himmme.com

    steps:
      - uses: actions/checkout@v4

      - name: Upload to Xserver (Staging)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SFTP_HOST_STG }}
          username: ${{ secrets.SFTP_USER_STG }}
          password: ${{ secrets.SFTP_PASS_STG }}
          source: "./*"          # ← dist ではなく、そのまま
          target: ${{ secrets.SFTP_PATH_STG }}
          rm: true               # 既存ファイル削除（任意）
