name: テストアップ(test.himmme.com)

on:
  push:
    branches:
      - main

jobs:
  deploy-staging:
    runs-on: ubuntu-latest

    environment:
      name: staging
      url: https://test.himmme.com

    steps:
      - uses: actions/checkout@v4

      # 必要に応じてビルド
      - name: Install & Build
        run: |
          npm install
          npm run build

      - name: Upload to Xserver (Staging)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SFTP_HOST_STG }}
          username: ${{ secrets.SFTP_USER_STG }}
          password: ${{ secrets.SFTP_PASS_STG }}
          source: "dist/*"
          target: ${{ secrets.SFTP_PATH_STG }}
